"use client";
import { AdminShell } from "@/components/admin/AdminShell";
import { authedPost, getCurrentUser } from "@/lib/auth";
import { getRTTData, RTTData } from "@/lib/googleData";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
export default function AdminDashboardPage() {
  const router = useRouter(); const [data,setData] = useState<RTTData|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{ const user=getCurrentUser(); if(!user || user.role!=="admin") router.push("/login"); getRTTData().then(setData); },[router]);
  async function syncNow(){ setBusy(true); try{ await authedPost("syncForm",{}); await authedPost("recalcStandings",{}); setData(await getRTTData()); alert("Synced and recalculated."); } catch(err){ alert(String(err)); } finally { setBusy(false); } }
  const liveMatch = data?.matches.find((m)=>(m.status||"").toLowerCase()==="live");
  return <AdminShell><p className="text-xs font-black uppercase tracking-[0.3em] text-rtt-red">Control Center</p><h1 className="mt-3 text-5xl font-black italic uppercase">Dashboard</h1><div className="mt-6 rounded-[2rem] border border-yellow-400/30 bg-yellow-400/10 p-5"><p className="text-sm font-black uppercase tracking-[0.18em] text-yellow-200">Operator Warning</p><p className="mt-2 text-sm leading-6 text-white/70">Do not rename sheet tabs or move columns. Use this dashboard for scoring and syncing.</p></div><div className="mt-8 grid gap-4 md:grid-cols-4"><button onClick={()=>router.push("/admin/matches")} className="rounded-[2rem] bg-rtt-red p-8 text-left text-2xl font-black uppercase shadow-2xl">Live Scoring<span className="mt-2 block text-sm font-bold normal-case text-white/70">Tap score buttons.</span></button><button onClick={()=>router.push("/admin/players")} className="rounded-[2rem] border border-white/10 bg-white/5 p-8 text-left text-2xl font-black uppercase">Players<span className="mt-2 block text-sm font-bold normal-case text-white/60">Review roster.</span></button><button onClick={()=>router.push("/live")} className="rounded-[2rem] border border-white/10 bg-white/5 p-8 text-left text-2xl font-black uppercase">Public Live<span className="mt-2 block text-sm font-bold normal-case text-white/60">Open scoreboard.</span></button><button disabled={busy} onClick={syncNow} className="rounded-[2rem] border border-white/10 bg-white/5 p-8 text-left text-2xl font-black uppercase disabled:opacity-50">Sync Now<span className="mt-2 block text-sm font-bold normal-case text-white/60">Pull forms and recalc.</span></button></div><div className="mt-8 grid gap-4 md:grid-cols-4"><Metric label="Players" value={data?.players.length||0}/><Metric label="Matches" value={data?.matches.length||0}/><Metric label="Prize Pool" value={`$${data?.payout.prizePool||0}`}/><Metric label="Winner" value={data?.payout.firstPlaceName||"TBD"}/></div><div className="mt-8 rounded-[2rem] border border-white/10 bg-white/[0.055] p-5"><p className="text-xs font-black uppercase tracking-[0.25em] text-rtt-red">Live Match Status</p>{liveMatch ? <p className="mt-3 text-2xl font-black uppercase">{liveMatch.playerA} {liveMatch.scoreA} - {liveMatch.scoreB} {liveMatch.playerB}</p> : <p className="mt-3 text-white/55">No active live match currently marked Live.</p>}</div></AdminShell>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[2rem] border border-white/10 bg-white/5 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-white/40">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>}
